#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$HOME/bin:$HOME/bin/SuperCollider:$HOME/Library/Haskell/bin:$HOME/.cabal/bin:/usr/local/bin:/usr/local/opt/ruby/bin:$HOME/src/music-suite/music-sandbox/bin:$PATH

# set the default system editor
export VISUAL='mvim -v'
export EDITOR='mvim -v'
export GIT_EDITOR='mvim -v'

alias tmux='tmux -2' # force tmux to assume 256color terminal
alias vim='mvim -v'

# zsh
bindkey '^R' history-incremental-search-backward

# set LANG
# LANG=en_US.UTF-8
# LC_CTYPE=en_US.UTF-8
# LC_MESSAGES=en_US.UTF-8

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
