#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$HOME/bin:$HOME/bin/SuperCollider:$HOME/Library/Haskell/bin:$HOME/.cabal/bin:/usr/local/bin:/usr/local/opt/ruby/bin:$HOME/src/music-suite/music-sandbox/bin:$PATH

# set the default system editor
export VISUAL='mvim -v'
export EDITOR='mvim -v'
export GIT_EDITOR='mvim -v'

alias tmux='tmux -2' # force tmux to assume 256color terminal
alias vim='mvim -v'

# zsh
bindkey '^R' history-incremental-search-backward

# Setup fuzzy bookmark search function
# ------------------------------------
unalias c 2> /dev/null
c() {
   local dest_dir=$(bookmarks_glob_echo | fzf)
   if [[ $dest_dir != '' ]]; then
      cd "$dest_dir"
   fi
}
export -f c > /dev/null

# add bookmark entry
unalias bkm 2> /dev/null
bkm() {
    bookmark_pwd
    echo "Added bookmark:" `pwd`
}
export -f bkm > /dev/null

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
